stages:name : Docker-Build
trigger:
  branches:
    include:
      - master
 

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: 'pipe'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
- task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: 'Push an image'
        imageName: 'piplo'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
